### ISSUE TITLE
Generate "default" .kube/config

### ISSUE THREAD

**Issue by cdrage** [cdrage/kubeshift#10]
Generate default .kube/config when deploying without specfiying a config file. (ex. unauthenticated, localhost api)

**Comment by shad7** [comment]
This is now possible like the following:

```python
>>> from kubeshift import Config
>>> cfg = Config(None)
>>> print(cfg.content)
{'current-context': None, 'apiVersion': 'v1', 'preferences': {}, 'users': [], 'contexts': [], 'clusters': [], 'kind': 'Config'}
>>> cfg.write_file()
```

`~/.kube/config`
```
apiVersion: v1
clusters: []
contexts: []
current-context: null
kind: Config
preferences: {}
users: []
```

Anything else for generating a default file with no specific inputs that you are looking for?

This makes no assumptions about Kubernetes or Openshift, protocol, ports, etc. Essentially an empty one.

**Comment by cdrage** [comment]
@shad7 Even though it's all blank, wouldn't you still have to supply a cluster end-point for the library to connect to?

**Comment by shad7** [comment]
That is correct if you were using `kubectl` or `oc`, but with kubeshift, the default server if one is not found within kubeconfig is to use `http://localhost:8080`. Just didn't want to assume that is always correct and write it explicitly to the config file itself. The default "name" for each entry is `self`, and that can be written but by exposing the `write_to_file` method, I leave that up to the user.

I'm open to suggestions of course :)
