### ISSUE TITLE
Task: Add doc generate and publish

### ISSUE THREAD

**Issue by shad7** [cdrage/kubeshift#28]
- [x] Add doc generation (docs directory, config, etc.)
- [x] Add publishing of docs to Github Pages
- [x] Resolve theme loading within gh-pages

**Comment by shad7** [comment]
@cdrage The publish task would have to fall to you after PR #29 is merged.

**Comment by cdrage** [comment]
Hey @shad7 anything I need to do my-end for this specific to Github? Create a kubeshift.github.io ?

**Comment by shad7** [comment]
I was assuming publishing to ReadTheDocs https://readthedocs.org/ The typical locations for most python projects. It will automatically build the docs as merges and tags happens based on configurations.

To use Github Pages, that would need to be scripted and manually published by you each time.

**Comment by shad7** [comment]
Here is what can be done to use GH Pages:

http://nikhilism.com/post/2012/automatic-github-pages-generation-from/

There are some one time setup tasks:

```
$ cd repo
$ git checkout --orphan gh-pages
$ git rm -rf .
$ echo "First commit" > index.html
$ git add .
$ git commit -m "Just to create the branch."
$ git push origin gh-pages
```

**Comment by shad7** [comment]
Also after some additional changes to the make file, and you setting credentials for github into travis, the travis.yml file can be updated to automatically update the documentation after a successful merge and build to master branch.

**Comment by shad7** [comment]
@cdrage After creating the `gh-pages` branch, just need the travis setup completed.

http://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci

**Comment by shad7** [comment]
![kubeshift-docs-errors](https://cloud.githubusercontent.com/assets/4284213/19075827/9be307ca-8a14-11e6-92ad-b18c4d3e27b2.PNG)

Seems the gh-pages is some how having issues loading the content from the directory.

**Comment by shad7** [comment]
@cdrage I found the issue with why the theme parts is not showing up. Any file or directory that starts with an underscore, do not get published. That can be overridden by adding a `_config.yml` that indicates to include the underscore directories. 

I can work on that later this evening and get a PR ready for review tomorrow.

**Comment by cdrage** [comment]
@shad7 Fixed! 

Followed this issue: https://github.com/jekyll/jekyll/issues/55 simply adding `.nojekyll` fixed it.
